[pytest]

addopts = --headed
          --browser=chromium
          --video=on
;          --screenshot=on
          --tracing=on
          --html=myReportGenerated.html --self-contained-html --capture=tee-sys